version: "3.3"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${DB_USERNAME} -p ${DB_PASSWORD} --quiet | grep 1
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - mongo-db-volumes:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "5605:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_CONTAINER_NAME}
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_PASSWORD}

    depends_on:
      - mongodb

volumes:
  mongo-db-volumes:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/mongo/'